// Copyright 2017 EasyStack, Inc.

/*
Keystone API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 3
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// RoleAssignmentListResponseWithNames struct for RoleAssignmentListResponseWithNames
type RoleAssignmentListResponseWithNames struct {
	Links           *Links                     `json:"links,omitempty"`
	RoleAssignments *[]RoleAssignmentWithNames `json:"role_assignments,omitempty"`
}

// NewRoleAssignmentListResponseWithNames instantiates a new RoleAssignmentListResponseWithNames object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRoleAssignmentListResponseWithNames() *RoleAssignmentListResponseWithNames {
	this := RoleAssignmentListResponseWithNames{}
	return &this
}

// NewRoleAssignmentListResponseWithNamesWithDefaults instantiates a new RoleAssignmentListResponseWithNames object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRoleAssignmentListResponseWithNamesWithDefaults() *RoleAssignmentListResponseWithNames {
	this := RoleAssignmentListResponseWithNames{}
	return &this
}

// GetLinks returns the Links field value if set, zero value otherwise.
func (o *RoleAssignmentListResponseWithNames) GetLinks() Links {
	if o == nil || o.Links == nil {
		var ret Links
		return ret
	}
	return *o.Links
}

// GetLinksOk returns a tuple with the Links field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RoleAssignmentListResponseWithNames) GetLinksOk() (*Links, bool) {
	if o == nil || o.Links == nil {
		return nil, false
	}
	return o.Links, true
}

// HasLinks returns a boolean if a field has been set.
func (o *RoleAssignmentListResponseWithNames) HasLinks() bool {
	if o != nil && o.Links != nil {
		return true
	}

	return false
}

// SetLinks gets a reference to the given Links and assigns it to the Links field.
func (o *RoleAssignmentListResponseWithNames) SetLinks(v Links) {
	o.Links = &v
}

// GetRoleAssignments returns the RoleAssignments field value if set, zero value otherwise.
func (o *RoleAssignmentListResponseWithNames) GetRoleAssignments() []RoleAssignmentWithNames {
	if o == nil || o.RoleAssignments == nil {
		var ret []RoleAssignmentWithNames
		return ret
	}
	return *o.RoleAssignments
}

// GetRoleAssignmentsOk returns a tuple with the RoleAssignments field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RoleAssignmentListResponseWithNames) GetRoleAssignmentsOk() (*[]RoleAssignmentWithNames, bool) {
	if o == nil || o.RoleAssignments == nil {
		return nil, false
	}
	return o.RoleAssignments, true
}

// HasRoleAssignments returns a boolean if a field has been set.
func (o *RoleAssignmentListResponseWithNames) HasRoleAssignments() bool {
	if o != nil && o.RoleAssignments != nil {
		return true
	}

	return false
}

// SetRoleAssignments gets a reference to the given []RoleAssignmentWithNames and assigns it to the RoleAssignments field.
func (o *RoleAssignmentListResponseWithNames) SetRoleAssignments(v []RoleAssignmentWithNames) {
	o.RoleAssignments = &v
}

func (o RoleAssignmentListResponseWithNames) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Links != nil {
		toSerialize["links"] = o.Links
	}
	if o.RoleAssignments != nil {
		toSerialize["role_assignments"] = o.RoleAssignments
	}
	return json.Marshal(toSerialize)
}

type NullableRoleAssignmentListResponseWithNames struct {
	value *RoleAssignmentListResponseWithNames
	isSet bool
}

func (v NullableRoleAssignmentListResponseWithNames) Get() *RoleAssignmentListResponseWithNames {
	return v.value
}

func (v *NullableRoleAssignmentListResponseWithNames) Set(val *RoleAssignmentListResponseWithNames) {
	v.value = val
	v.isSet = true
}

func (v NullableRoleAssignmentListResponseWithNames) IsSet() bool {
	return v.isSet
}

func (v *NullableRoleAssignmentListResponseWithNames) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRoleAssignmentListResponseWithNames(val *RoleAssignmentListResponseWithNames) *NullableRoleAssignmentListResponseWithNames {
	return &NullableRoleAssignmentListResponseWithNames{value: val, isSet: true}
}

func (v NullableRoleAssignmentListResponseWithNames) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRoleAssignmentListResponseWithNames) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
