/*
Keystone API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 3
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// SelfLink The links to the resource.
type SelfLink struct {
	Self NullableString `json:"self,omitempty"`
}

// NewSelfLink instantiates a new SelfLink object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSelfLink() *SelfLink {
	this := SelfLink{}
	var self string = "null"
	this.Self = *NewNullableString(&self)
	return &this
}

// NewSelfLinkWithDefaults instantiates a new SelfLink object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSelfLinkWithDefaults() *SelfLink {
	this := SelfLink{}
	var self string = "null"
	this.Self = *NewNullableString(&self)
	return &this
}

// GetSelf returns the Self field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *SelfLink) GetSelf() string {
	if o == nil || o.Self.Get() == nil {
		var ret string
		return ret
	}
	return *o.Self.Get()
}

// GetSelfOk returns a tuple with the Self field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *SelfLink) GetSelfOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Self.Get(), o.Self.IsSet()
}

// HasSelf returns a boolean if a field has been set.
func (o *SelfLink) HasSelf() bool {
	if o != nil && o.Self.IsSet() {
		return true
	}

	return false
}

// SetSelf gets a reference to the given NullableString and assigns it to the Self field.
func (o *SelfLink) SetSelf(v string) {
	o.Self.Set(&v)
}

// SetSelfNil sets the value for Self to be an explicit nil
func (o *SelfLink) SetSelfNil() {
	o.Self.Set(nil)
}

// UnsetSelf ensures that no value is present for Self, not even an explicit nil
func (o *SelfLink) UnsetSelf() {
	o.Self.Unset()
}

func (o SelfLink) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Self.IsSet() {
		toSerialize["self"] = o.Self.Get()
	}
	return json.Marshal(toSerialize)
}

type NullableSelfLink struct {
	value *SelfLink
	isSet bool
}

func (v NullableSelfLink) Get() *SelfLink {
	return v.value
}

func (v *NullableSelfLink) Set(val *SelfLink) {
	v.value = val
	v.isSet = true
}

func (v NullableSelfLink) IsSet() bool {
	return v.isSet
}

func (v *NullableSelfLink) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSelfLink(val *SelfLink) *NullableSelfLink {
	return &NullableSelfLink{value: val, isSet: true}
}

func (v NullableSelfLink) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSelfLink) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
