// Copyright 2017 EasyStack, Inc.

/*
Keystone API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 3
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// RoleAssignmentListResponse struct for RoleAssignmentListResponse
type RoleAssignmentListResponse struct {
	Links           *Links            `json:"links,omitempty"`
	RoleAssignments *[]RoleAssignment `json:"role_assignments,omitempty"`
}

// NewRoleAssignmentListResponse instantiates a new RoleAssignmentListResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRoleAssignmentListResponse() *RoleAssignmentListResponse {
	this := RoleAssignmentListResponse{}
	return &this
}

// NewRoleAssignmentListResponseWithDefaults instantiates a new RoleAssignmentListResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRoleAssignmentListResponseWithDefaults() *RoleAssignmentListResponse {
	this := RoleAssignmentListResponse{}
	return &this
}

// GetLinks returns the Links field value if set, zero value otherwise.
func (o *RoleAssignmentListResponse) GetLinks() Links {
	if o == nil || o.Links == nil {
		var ret Links
		return ret
	}
	return *o.Links
}

// GetLinksOk returns a tuple with the Links field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RoleAssignmentListResponse) GetLinksOk() (*Links, bool) {
	if o == nil || o.Links == nil {
		return nil, false
	}
	return o.Links, true
}

// HasLinks returns a boolean if a field has been set.
func (o *RoleAssignmentListResponse) HasLinks() bool {
	if o != nil && o.Links != nil {
		return true
	}

	return false
}

// SetLinks gets a reference to the given Links and assigns it to the Links field.
func (o *RoleAssignmentListResponse) SetLinks(v Links) {
	o.Links = &v
}

// GetRoleAssignments returns the RoleAssignments field value if set, zero value otherwise.
func (o *RoleAssignmentListResponse) GetRoleAssignments() []RoleAssignment {
	if o == nil || o.RoleAssignments == nil {
		var ret []RoleAssignment
		return ret
	}
	return *o.RoleAssignments
}

// GetRoleAssignmentsOk returns a tuple with the RoleAssignments field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RoleAssignmentListResponse) GetRoleAssignmentsOk() (*[]RoleAssignment, bool) {
	if o == nil || o.RoleAssignments == nil {
		return nil, false
	}
	return o.RoleAssignments, true
}

// HasRoleAssignments returns a boolean if a field has been set.
func (o *RoleAssignmentListResponse) HasRoleAssignments() bool {
	if o != nil && o.RoleAssignments != nil {
		return true
	}

	return false
}

// SetRoleAssignments gets a reference to the given []RoleAssignment and assigns it to the RoleAssignments field.
func (o *RoleAssignmentListResponse) SetRoleAssignments(v []RoleAssignment) {
	o.RoleAssignments = &v
}

func (o RoleAssignmentListResponse) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Links != nil {
		toSerialize["links"] = o.Links
	}
	if o.RoleAssignments != nil {
		toSerialize["role_assignments"] = o.RoleAssignments
	}
	return json.Marshal(toSerialize)
}

type NullableRoleAssignmentListResponse struct {
	value *RoleAssignmentListResponse
	isSet bool
}

func (v NullableRoleAssignmentListResponse) Get() *RoleAssignmentListResponse {
	return v.value
}

func (v *NullableRoleAssignmentListResponse) Set(val *RoleAssignmentListResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableRoleAssignmentListResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableRoleAssignmentListResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRoleAssignmentListResponse(val *RoleAssignmentListResponse) *NullableRoleAssignmentListResponse {
	return &NullableRoleAssignmentListResponse{value: val, isSet: true}
}

func (v NullableRoleAssignmentListResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRoleAssignmentListResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
