// Copyright 2017 EasyStack, Inc.

/*
Keystone API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 3
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// RoleAssignmentListResponseRole struct for RoleAssignmentListResponseRole
type RoleAssignmentListResponseRole struct {
	Id *string `json:"id,omitempty"`
}

// NewRoleAssignmentListResponseRole instantiates a new RoleAssignmentListResponseRole object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRoleAssignmentListResponseRole() *RoleAssignmentListResponseRole {
	this := RoleAssignmentListResponseRole{}
	return &this
}

// NewRoleAssignmentListResponseRoleWithDefaults instantiates a new RoleAssignmentListResponseRole object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRoleAssignmentListResponseRoleWithDefaults() *RoleAssignmentListResponseRole {
	this := RoleAssignmentListResponseRole{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *RoleAssignmentListResponseRole) GetId() string {
	if o == nil || o.Id == nil {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RoleAssignmentListResponseRole) GetIdOk() (*string, bool) {
	if o == nil || o.Id == nil {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *RoleAssignmentListResponseRole) HasId() bool {
	if o != nil && o.Id != nil {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *RoleAssignmentListResponseRole) SetId(v string) {
	o.Id = &v
}

func (o RoleAssignmentListResponseRole) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Id != nil {
		toSerialize["id"] = o.Id
	}
	return json.Marshal(toSerialize)
}

type NullableRoleAssignmentListResponseRole struct {
	value *RoleAssignmentListResponseRole
	isSet bool
}

func (v NullableRoleAssignmentListResponseRole) Get() *RoleAssignmentListResponseRole {
	return v.value
}

func (v *NullableRoleAssignmentListResponseRole) Set(val *RoleAssignmentListResponseRole) {
	v.value = val
	v.isSet = true
}

func (v NullableRoleAssignmentListResponseRole) IsSet() bool {
	return v.isSet
}

func (v *NullableRoleAssignmentListResponseRole) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRoleAssignmentListResponseRole(val *RoleAssignmentListResponseRole) *NullableRoleAssignmentListResponseRole {
	return &NullableRoleAssignmentListResponseRole{value: val, isSet: true}
}

func (v NullableRoleAssignmentListResponseRole) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRoleAssignmentListResponseRole) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
