// Copyright 2017 EasyStack, Inc.

/*
Keystone API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 3
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// ApplicationCredentialCreateRequest struct for ApplicationCredentialCreateRequest
type ApplicationCredentialCreateRequest struct {
	ApplicationCredential ApplicationCredentialCreate `json:"application_credential"`
}

// NewApplicationCredentialCreateRequest instantiates a new ApplicationCredentialCreateRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApplicationCredentialCreateRequest(applicationCredential ApplicationCredentialCreate) *ApplicationCredentialCreateRequest {
	this := ApplicationCredentialCreateRequest{}
	this.ApplicationCredential = applicationCredential
	return &this
}

// NewApplicationCredentialCreateRequestWithDefaults instantiates a new ApplicationCredentialCreateRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApplicationCredentialCreateRequestWithDefaults() *ApplicationCredentialCreateRequest {
	this := ApplicationCredentialCreateRequest{}
	return &this
}

// GetApplicationCredential returns the ApplicationCredential field value
func (o *ApplicationCredentialCreateRequest) GetApplicationCredential() ApplicationCredentialCreate {
	if o == nil {
		var ret ApplicationCredentialCreate
		return ret
	}

	return o.ApplicationCredential
}

// GetApplicationCredentialOk returns a tuple with the ApplicationCredential field value
// and a boolean to check if the value has been set.
func (o *ApplicationCredentialCreateRequest) GetApplicationCredentialOk() (*ApplicationCredentialCreate, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ApplicationCredential, true
}

// SetApplicationCredential sets field value
func (o *ApplicationCredentialCreateRequest) SetApplicationCredential(v ApplicationCredentialCreate) {
	o.ApplicationCredential = v
}

func (o ApplicationCredentialCreateRequest) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["application_credential"] = o.ApplicationCredential
	}
	return json.Marshal(toSerialize)
}

type NullableApplicationCredentialCreateRequest struct {
	value *ApplicationCredentialCreateRequest
	isSet bool
}

func (v NullableApplicationCredentialCreateRequest) Get() *ApplicationCredentialCreateRequest {
	return v.value
}

func (v *NullableApplicationCredentialCreateRequest) Set(val *ApplicationCredentialCreateRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableApplicationCredentialCreateRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableApplicationCredentialCreateRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApplicationCredentialCreateRequest(val *ApplicationCredentialCreateRequest) *NullableApplicationCredentialCreateRequest {
	return &NullableApplicationCredentialCreateRequest{value: val, isSet: true}
}

func (v NullableApplicationCredentialCreateRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApplicationCredentialCreateRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
