/*
Keystone API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 3
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// UserGetResponse struct for UserGetResponse
type UserGetResponse struct {
	User *User `json:"user,omitempty"`
}

// NewUserGetResponse instantiates a new UserGetResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUserGetResponse() *UserGetResponse {
	this := UserGetResponse{}
	return &this
}

// NewUserGetResponseWithDefaults instantiates a new UserGetResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUserGetResponseWithDefaults() *UserGetResponse {
	this := UserGetResponse{}
	return &this
}

// GetUser returns the User field value if set, zero value otherwise.
func (o *UserGetResponse) GetUser() User {
	if o == nil || o.User == nil {
		var ret User
		return ret
	}
	return *o.User
}

// GetUserOk returns a tuple with the User field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UserGetResponse) GetUserOk() (*User, bool) {
	if o == nil || o.User == nil {
		return nil, false
	}
	return o.User, true
}

// HasUser returns a boolean if a field has been set.
func (o *UserGetResponse) HasUser() bool {
	if o != nil && o.User != nil {
		return true
	}

	return false
}

// SetUser gets a reference to the given User and assigns it to the User field.
func (o *UserGetResponse) SetUser(v User) {
	o.User = &v
}

func (o UserGetResponse) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.User != nil {
		toSerialize["user"] = o.User
	}
	return json.Marshal(toSerialize)
}

type NullableUserGetResponse struct {
	value *UserGetResponse
	isSet bool
}

func (v NullableUserGetResponse) Get() *UserGetResponse {
	return v.value
}

func (v *NullableUserGetResponse) Set(val *UserGetResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableUserGetResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableUserGetResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUserGetResponse(val *UserGetResponse) *NullableUserGetResponse {
	return &NullableUserGetResponse{value: val, isSet: true}
}

func (v NullableUserGetResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUserGetResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
